### ISSUE TITLE
It should be mentioned in the Readme that a Counter is a Multiset/Bag

### ISSUE THREAD

**Issue by oxinabox** [JuliaCollections/DataStructures.jl#133]
Today I needed a [Multiset](https://en.wikipedia.org/wiki/Multiset)
I noted before that there was not on in Core or in this package.

I started to think about how I would implement one quickly/simply.
One implementation would be a dictionary, storing what is in the multiset and how many times it occurs.
But of-course that is just a Counter.

It should be in the readme so this package comes up when people google "Julia multiset"

**Comment by oxinabox** [comment]
Though before making that change,
it makes sense for Accumulators (and thus counters) to implement `(==)` and `hash` since Sets do.

I can make a pull request for these changes.
I have the code for that -- it is just delgating it to the Accumulator.map since Dicts implement that.

**Comment by rawls238** [comment]
@oxinabox feel free to make a PR for these changes
