### ISSUE TITLE
Proposal: Huffman Tree

### ISSUE THREAD

**Issue by sisirkoppaka** [JuliaCollections/DataStructures.jl#183]
I was coding up a Huffman tree for usage with NLP applications. I'd like to contribute it to this package, if the maintainers are interested. Could you let me know?

**Comment by rawls238** [comment]
I think that would be useful, put up a PR for it?

**Comment by sisirkoppaka** [comment]
Sure, will open a WIP one soon. Thanks!

**Comment by oxinabox** [comment]
Since this has not eventuated.
And its lack is not pressing,
is there a reason to keep this open?

**Comment by sisirkoppaka** [comment]
Okay sure, closing it.
