### ISSUE TITLE
Proposal: most_common() for counters

### ISSUE THREAD

**Issue by ymer** [JuliaCollections/DataStructures.jl#195]
Similar to most_common() for Counter in collections in python. This is a frequent use of counters for me.

Example:

most_common(counter([1, 6, 2, 2, 5, 5, 5]))

4-element Array{Tuple{Int64,Int64},1}:
 (5,3)
 (2,2)
 (1,1)
 (6,1)

**Comment by kmsquire** [comment]
Sounds good.  Care to take a crack at implementing it?

**Comment by ymer** [comment]
On second thought, maybe it should be an Array of Pairs.

`most_common(ct::Accumulator) = sort(collect(ct.map), by=p->p[2], rev=true)`

4-element Array{Pair{Int64,Int64},1}:
 5=>3
 2=>2
 6=>1
 1=>1

How does this look? I'm unsure about the 'p'.

**Comment by laborg** [comment]
This was implemented in https://github.com/JuliaCollections/DataStructures.jl/pull/375
