### ISSUE TITLE
DefaultDict and DefaultOrderedDict don't work for some cases

### ISSUE THREAD

**Issue by xqrongm** [JuliaCollections/DataStructures.jl#205]
I apologize if this is a duplicated issue.

Julia version 0.4.6. DataStructures version 0.4.4

![image](https://cloud.githubusercontent.com/assets/12205732/16354353/1eadf27e-3a5f-11e6-93a7-0ee6ba3bf7ca.png)

![image](https://cloud.githubusercontent.com/assets/12205732/16354346/e95331d4-3a5e-11e6-8e35-403f6ced08c4.png)

**Comment by rawls238** [comment]
thanks for reporting this, will try to see what's going on

**Comment by oxinabox** [comment]
This is no longer reproducible on any current version.
So I believe this can be closed.

**Comment by kmsquire** [comment]
Thanks!
