### ISSUE TITLE
Splay tree

### ISSUE THREAD

**Issue by dawidip** [JuliaCollections/DataStructures.jl#232]
Hi! I'd like to help to improve this package. I've taken look at desired data structures and seen that you need splay tree. Please let me know if I can code it for this package :)

**Comment by PallHaraldsson** [comment]
@dawidip Feel free to implement (any) data structure. I'm sure it will be accepted (or at least considered; I have no power to merge.. I'm guessing for others).

If not, you can make your own package.

[I also proposed doubly-linked unrolled list.. I may do it someday; would rather do other stuff first; better sort..]

**Comment by laborg** [comment]
Has been implemented in https://github.com/JuliaCollections/DataStructures.jl/pull/645
