### ISSUE TITLE
eval in the latest master

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaCollections/DataStructures.jl#258]
The latest DataStructures.jl master uses an `eval` to deal with the the `where` syntax of the new type system, presumably because it won't parse in older versions of Julia and hence cannot be guarded with the usual `if` test on the version number.  I'd just like to point out that, according to the documentation on the new type system, there is an alternative syntax for `where` that should at least be parseable, if meaningless, in older versions:
According to the docs:

The syntax `Array{T} where T<:Integer` is lowered to
```julia
    let T = TypeVar(:T,Integer)
        UnionAll(T, Array{T})
    end
```

**Comment by kmsquire** [comment]
@StephenVavasis, thanks for the suggestion.  Can you point to the documentation for this?

**Comment by StephenVavasis** [comment]
The above quote was taken from the section entitled "More about types" in the developer docs in the latest documentation:

http://docs.julialang.org/en/latest/devdocs/types.html

Unfortunately, this chapter of the documentation is garbled because of a misplaced quotation mark (which I already reported as a Julia issue: https://github.com/JuliaLang/julia/issues/20093).

**Comment by kmsquire** [comment]
One of the `evals` is on a construct that does not use `where` and is parseable, so I remove it in #260.

(@StephenVavasis, unrelated, but any chance you can review #168?)

**Comment by kmsquire** [comment]
Minor update here: `eval(parse(...))` has been changed to `include_string(...)` in #265, as suggested by @tkelman in #260.  This isn't really fundamentally different, but a quick attempt suggested getting a parseable version isn't exactly straightforward (although I thought @vtjnash might have done so in `JLD.jl` or some other package).

**Comment by oxinabox** [comment]
This can be closed now
