### ISSUE TITLE
Move this package to JuliaCollections organization?

### ISSUE THREAD

**Issue by tkelman** [JuliaCollections/DataStructures.jl#261]
Ref https://github.com/JuliaLang/Iterators.jl/issues/96 - I've invited most recent contributors there, any objections to doing this? Would help separate the CI queue here from Base.

After moving we'd need to make sure Travis and AppVeyor are re-enabled, and update the url in metadata.

**Comment by tkelman** [comment]
Ref https://github.com/JuliaLang/Iterators.jl/issues/96#issuecomment-275897456 there's a decision to be made whether JuliaContainers should be renamed to JuliaCollections, or leaving it with its current name, before moving some packages over

**Comment by tkelman** [comment]
Done. @kmsquire you probably need to manually re-enable appveyor.

**Comment by kmsquire** [comment]
Thanks.  I think I've re-enabled AppVeyor.  I triggered a build there, will try closing and reopening a PR.
