### ISSUE TITLE
Should `pop!(::Accumulator, v)` set the count of `v` to zero, or just decrement it

### ISSUE THREAD

**Issue by oxinabox** [JuliaCollections/DataStructures.jl#285]
Currently `push!(ct::Accumuator, v)` increase the count of `v` by 1.
`pop!` is the logical oposite of `push!`, so it could be expected to decrement it by 1.
But currently it removes `v` entirely -- setting it's count to zero.

The manual for `pop!` in base is:

> 
> Base.pop! — Method.
> 
> pop!(collection, key[, default])
> 
> Delete and return the mapping for key if it exists in collection, otherwise return default, or throw an error if default is not specified.

And also:

> 
> Base.pop! — Method.
> 
> pop!(collection) -> item
> 
> Remove an item in collection and return it. If collection is an ordered container, the last item is returned.

You can see the definition is for indexed collections with Dict-like behavour.
This is our current behavour.

The second definition is for non-indexed collections with Stack like behavour.
(though the main user `Vector` is indexed, the index is not used).

If we think of Accumulator as being like a `DefaultDict{T, Int}`, with a default value of `0`.
Then the current behavior of resetting the count to zero makes sense.

If on the otherhand, we think of it as a Multiset / Bag (#133).
Then it makes sense for `pop!` to delete only the last copy of that item added to the bad.
i.e. reducing its count by one.

**Comment by kmsquire** [comment]
@oxinabox, do you have a use case that suggests one use case over the other?

To me, this suggests that `push!` and `pop!` are the wrong functions to be using for accumulating values, or at least that it would probably be useful to have an alternative to `pop!` when treating an Accumulator like a Multiset/Bag.  

Maybe `pop_one!`?

**Comment by oxinabox** [comment]
Could deprecate `push!`, and  just have `inc` and `dec`.
Maybe also deprecate `pop!` for `reset!`.
Thus thinking about this as a thing that counts -- a counter if you like :-P.

I only noticed this because I wanted to decrements the count sometimes in a for-loop.
I thought since I was using `push!` elsewhere in the loop for incrementing, `pop!` would decrement.
Right now the only way to `dec` is `push!(counter, key,  -1)`
Set index also needs overloading -- with sent index overloaded there is the nice: `counter[key]-=1`

**Comment by cstjean** [comment]
I agree with @oxinabox: if `push!` increments, `pop!` should decrement. Perhaps `delete!` should be used to delete an element? It's already used this way in `dict`. I can't imagine too many uses of the current `pop!`.

My use case: I do recursive traversal of a tree, and I need to know whether an element has been encountered in a node's ancestors. `push!/pop!` over a counter would be the easiest way to do this.
