### ISSUE TITLE
PriorityQueue - peek versus dequeue!

### ISSUE THREAD

**Issue by KristofferC** [JuliaCollections/DataStructures.jl#289]
Moved from https://github.com/JuliaLang/julia/issues/18517

-----------------

`peek` returns the pair `(key,value)` whereas `dequeue!` only returns the `key`:

``` julia
using Base.Collections
pq = PriorityQueue()
enqueue!(pq, key, value)
key, value = peek(pq)
key = dequeue!(pq)
```

Can `dequeue!` return the pair?

To be consistent with the rest of the interface, should we rename some of these to `push!` and `pop!`?

**Comment by sbromberger** [comment]
👍 to this request - it's very helpful to have the value on dequeue. Right now I'm not sure there's an efficient way to get the value. The closest I can think of is @KristofferC's code above, which requires two commands (one to get the value, the other to pop the key).
