### ISSUE TITLE
Two-argument `merge!` and `push!` are the same for accumulators

### ISSUE THREAD

**Issue by cstjean** [JuliaCollections/DataStructures.jl#303]
```julia
ct1() = counter(abs.(-5:5))
ct2() = counter([1,2,1,4,5,6])

push!(ct1(), ct2()) == merge!(ct1(), ct2())   # true
```

Why? Semantically, it doesn't make much sense, and pragmatically, it's a needless special-case that precludes having a counter-of-counter.

**Comment by kmsquire** [comment]
I agree that this doesn't make much sense. The `push!` function taking two accumulators should get renamed to `merge!` and the alternative which accepts two or more accumulators should be change to accept 3 or more. 

(Probably needs a deprecation as well, with an end point of Julia v0.7 or 1.0)
