### ISSUE TITLE
Why PriorityQueue(K,V) instead of PriorityQueue{K,V}()?

### ISSUE THREAD

**Issue by cossio** [JuliaCollections/DataStructures.jl#312]
It seems to me that we should have `PriorityQueue{K,V}()`, instead of `PriorityQueue(K,V)` (where `K`,`V` are types), since this is more consistent with the way type parameters are treated in Julia.

**Comment by kmsquire** [comment]
Yes, I also noticed this the other day.  This should definitely be changed--just that no one has gotten around to it.  Are you up to creating a pull request?

**Comment by kmsquire** [comment]
Implemented in #316
