### ISSUE TITLE
Implement empty!() for CircularBuffer and add CircularBuffer to docs

### ISSUE THREAD

**Issue by KadeG** [JuliaCollections/DataStructures.jl#314]
empty!(CircularBuffer) would be nicer to use than recreating it. CircularBuffer has auto-eviction while CircularDeque does not, so it warrants an entry in the docs.

**Comment by kmsquire** [comment]
Thanks for creating this issue.  Do feel up to submitting a pull request?

**Comment by KadeG** [comment]
I'd love to. It may be terrible- I'm new to this.

**Comment by kmsquire** [comment]
No worries--I and others will try to give good feedback.  Give it a try!

**Comment by KadeG** [comment]
[`CircularDeque`'s](https://github.com/JuliaCollections/DataStructures.jl/blob/master/src/circ_deque.jl) `empty!()` does not seem to actually delete anything. Is this faster than actually deleating things like in [`array.jl`](https://github.com/JuliaLang/julia/blob/master/base/array.jl) using `_deleteend!(a::Vector, delta::Integer) = ccall(:jl_array_del_end, Void, (Any, UInt), a, delta)` ? 

Since `CircularBuffer` doesn't have `n` `first`, and `last` to reset, would recreating the buffer as an empty `vector` of type `T` work?
```
function Base.empty!(cb::CircularBuffer)
    cb.buffer = typeof(cb.buffer)[]
    cb
end
```

Sidenote: [`CircularDeque`'s](https://github.com/JuliaCollections/DataStructures.jl/blob/master/src/circ_deque.jl) docstring `Create a double-ended queue of maximum capacity 'n'` is a bit confusing because `n` is used as the number of elements currently contained in `empty!()`, not the maximum capacity.

**Comment by KadeG** [comment]
This is now #317 . Closing the issue.
