### ISSUE TITLE
Default of `[]` for DefaultDict gives unexpected results. 

### ISSUE THREAD

**Issue by davidavdav** [JuliaCollections/DataStructures.jl#318]
Hello, I was somewhat surprised that 
```julia
d = DefaultDict{AbstractString, Vector{Int}}(Int[])
push!(d["a"], 1)
push!(d["b"], 2)
d
DataStructures.DefaultDict{AbstractString,Array{Int64,1},Array{Int64,1}} with 2 entries:
  "b" => [1, 2]
  "a" => [1, 2]
```
It looks like the default value `Int[]` is cashed, and shared between the entries of `d`.  Replacing this with `Vector{Int}` resolves the problem for me, but I find the behaviour counterintuitive.

**Comment by yuyichao** [comment]
This is expected and is true for any mutable objects.

**Comment by kmsquire** [comment]
This is mentioned at the end of the documentation here: http://datastructuresjl.readthedocs.io/en/latest/default_dict.html

Not sure if you've used dictionaries with defaults elsewhere, but, e.g., Python's defaultdict works the same way (although there, I believe you're required to use functions for all defaults).

**Comment by davidavdav** [comment]
Thanks, after I ran into this I did see that the last example in the docs actually was dealing with this.  I would argue that that still is a little convolved example, and my bad, wicked, misguided intuition of using `[]` as an initializer is a slightly more obvious pitfall for the uninitiated.

**Comment by kmsquire** [comment]
> my bad, wicked, misguided intuition of using [] as an initializer is a slightly more obvious pitfall for the uninitiated.

😅 Yeah, it is a pretty common pitfall.  Some thoughts: 

We could require a user to us a function that provides the default value (ala Python). This is currently optional. However, it seems silly for bits types and other truly immutable values. 

We could try to warn the user when they provide a shared container (Array, Dict, etc) or other mutable type. However, it's unclear how to do this without enumerating all types. 

... I don't have any other ideas off of the top of my head. Thoughts?

**Comment by davidavdav** [comment]
Perhaps check if the initializer type is mutable https://stackoverflow.com/questions/40706962/how-to-check-a-type-for-mutability , and if so, issue a warning or generously intialize with a copy?
