### ISSUE TITLE
Trie "seen_prefix" example doesn't work

### ISSUE THREAD

**Issue by goretkin** [JuliaCollections/DataStructures.jl#319]
Following the example on https://github.com/JuliaCollections/DataStructures.jl/blob/7178c6082cc973599bd3ec897eaa8d430c112b98/doc/source/trie.rst 

```julia
julia> using DataStructures

julia> t = Trie(["apple", "apply", "application", "appetizer"])
DataStructures.Trie{Void}(nothing, Dict('a'=>DataStructures.Trie{Void}(nothing, Dict('p'=>DataStructures.Trie{Void}(nothing, Dict('p'=>DataStructures.Trie{Void}(nothing, Dict('l'=>DataStructures.Trie{Void}(nothing, Dict('y'=>DataStructures.Trie{Void}(nothing, Dict{Char,DataStructures.Trie{Void}}(), true),'i'=>DataStructures.Trie{Void}(nothing, Dict('c'=>DataStructures.Trie{Void}(nothing, Dict('a'=>DataStructures.Trie{Void}(nothing, Dict('t'=>DataStructures.Trie{Void}(nothing, Dict('i'=>DataStructures.Trie{Void}(nothing, Dict('o'=>DataStructures.Trie{Void}(nothing, Dict('n'=>DataStructures.Trie{Void}(nothing, Dict{Char,DataStructures.Trie{Void}}(), true)), false)), false)), false)), false)), false)), false),'e'=>DataStructures.Trie{Void}(nothing, Dict{Char,DataStructures.Trie{Void}}(), true)), false),'e'=>DataStructures.Trie{Void}(nothing, Dict('t'=>DataStructures.Trie{Void}(nothing, Dict('i'=>DataStructures.Trie{Void}(nothing, Dict('z'=>DataStructures.Trie{Void}(nothing, Dict('e'=>DataStructures.Trie{Void}(nothing, Dict('r'=>DataStructures.Trie{Void}(nothing, Dict{Char,DataStructures.Trie{Void}}(), true)), false)), false)), false)), false)), false)), false)), false)), false)), false)

julia> seen_prefix(t::Trie, str) = any(v -> v.is_key, path(t, str))
seen_prefix (generic function with 1 method)

julia> seen_prefix(t, "app")
false

julia> seen_prefix(t, "apple")
true

julia> seen_prefix(t, "appl")
false

julia> seen_prefix(t, "apply")
true

julia> seen_prefix(t, "appli")
false

julia> seen_prefix(t, "application")
true
```

Many of those calls to `seen_prefix` return false `false`s.

One (ugly) version that appears to work is
```
seen_prefix(t::Trie, str) = length(collect(path(t, str))) - 1 == length(str)
```

**Comment by oxinabox** [comment]
It is unclear as to what the `seen_prefix` example is mean to be doing.
`seen` is an unclear word. Does it mean `contains`, or does it mean `passed through`

>For example, to test whether a trie contains any prefix of a given string, use:
> `seen_prefix(t::Trie, str) = any(v -> v.is_key, path(t, str))`

I would say the current behaviour is correct.
It means `seen_prefix(t,str)` means was any prefix of the `str` added to the trie.

That is the there were no prefixes for any of the word you used `seen_prefix` on that fail, 
that ever been added to the Trie.


If you had done:
`t = Trie(["apple", "apply", "application", "appetizer", "ap"])`
Then they would app pass. As every word you tested did have `ap` as a prefix,
and `ap` is a word that is in the trie.


For what you want, which seems to "be there is a word with has my full str as a prefix".
then you will want different code.
`used_whole_prefix(t, str)= subtrie(t, str) !=nothing`

**Comment by goretkin** [comment]
Ah, I see. I guess I had it it sort of backwards. I should read it was

"For example, to test whether the prefix of a given string is in the trie ..."

`subtrie` makes perfect sense for what I wanted (which was, I think, word completion?) I hadn't come across it.

**Comment by goretkin** [comment]
I added an example of `subtrie` to the documentation: https://github.com/JuliaCollections/DataStructures.jl/pull/337
