### ISSUE TITLE
Proposal: Judydicts/Judyarrays for sorted dict

### ISSUE THREAD

**Issue by bbrehm** [JuliaCollections/DataStructures.jl#332]
You might consider switching the 2/3 tree to judy. 

I wrote a paper-thin wrapper for the terrible C-API, check  
[https://github.com/bbrehm/judydict.jl]

Upshot: My distro's judy binary beat SortedDict by a factor of ~3, bigger factor for larger arrays. judy is much more space efficient (even though I tested with the worst case for judy, where keys are relatively uniformly distributed-- a better and quite common case is if your Int64s are really UInt32, then Judy will compress the common prefix). Judy supports queries for the Nth item in sort order, and can rapidly count items in an interval.

Judy is almost but not quite competitive with unsorted Dicts, but iterating over all key/value pairs is too common and too slow to ever consider switching out Base.Dict.

Of course, one would need to figure out a sensible julia API, and especially a sensible way of keeping objects alive.

I personally need judy for a project involving sparse vectors.

**Comment by StephenVavasis** [comment]
I am not familiar with Judy arrays.  I spent a few minutes searching for them on the internet and couldn't find a clear explanation.  There does not appear to be a proper literature publication of the technique.  Furthermore, the intellectual property situation of the code and documentation seems to be unclear.   What I was able to determine is that they are somehow optimized for cache and memory hierarchy.  

It is indeed true that the 2-3-tree implementation underlying SortedDict is not optimized for cache or memory hierarchy, and that this is a significant performance drain.  Currently there is a pull request (WIP) https://github.com/JuliaCollections/DataStructures.jl/pull/241 for an implementation of a cache-optimized balanced-tree structure.  I don't think there is a projected completion date for that PR.

**Comment by quinnj** [comment]
There is https://github.com/tanmaykm/JudyDicts.jl, but it hasn't been updated in a while.

**Comment by bbrehm** [comment]
Yeah, the documentation is really terrible, both the algorithm and the API. judyarrays are essentially radix trees, with an ungodly number of different node types, depending on how full the node is.

The "standard" implementation of judy is owned by Hewlett-Packard and is LGPL; most Linux distros have a package. I guess the license is acceptable, since we would only link to it? 

I originally tried  [https://github.com/tanmaykm/JudyDicts.jl](url) as well, but in the end decided to rewrite the entire thing, since it did not play on newer julia versions and tried to handle objects, instead of just raw ints.

A minimal wrapper that works with current julia is on [https://github.com/bbrehm/judydict.jl](url). This should be enough to understand the easy parts of the API and run some benchmarks, until a decision is reached whether a proper wrapper would be worth the effort. Since I am rather new to julia, I would leave the production code on widely used libraries to others.

My guess for keeping objects alive/storing references would be an array of living objects and a stack of free-slot offsets into this array. Then, judy stores key => offset into this array of living objects. That way, we get O(1) access to objects, and the free-slot stack ensures that we don't fragment too much. The memory access patterns into the array of living objects is not very cache-friendly if users want to iterate all key/value pairs in sort order, though. On the other hand, this gives a fast unsorted iteration over living values; if we splurge on memory, we could even store keys along with values, giving fast unsorted iterators over (key,value)-pairs. We would need to do a little bit of pointer-arithmetic to C_NULL references on removal from the judydict (we don't want to accidentally keep objects alive).

This way, we could even allow users to store a gratis extra 30 bit of tags/flags in their values, assuming that the judyarray does not attempt to simultaneously hold more that 2^34 key/value pairs.

**Comment by oxinabox** [comment]
I would like it if DataStructures.jl stayed pure julia.
Without binary dependencies.
It keeps in maintainable, and portable.

I'm not against the use of data structures with binary backing, but I don't think they should be in DataStructures.jl.

**Comment by oxinabox** [comment]
I am closing this for now.
Feel free to create a separate wrapper package.
Or to open a PR with a pure julia implementation at some later date.
