### ISSUE TITLE
Use of rehash! in pure functions for OrderedDict and OrderedSet

### ISSUE THREAD

**Issue by bkamins** [JuliaCollections/DataStructures.jl#335]
Related to https://github.com/JuliaLang/julia/pull/24345.
Actually there are more places here, where `rehash!` is called in functions that should be pure, e.g. `start`.

If this is not fixed earlier I can work on this when https://github.com/JuliaLang/julia/pull/24345 is finished.

**Comment by oxinabox** [comment]
Closing due to moved to https://github.com/JuliaCollections/OrderedCollections.jl/issues/9
