### ISSUE TITLE
CircularDeque is not 'circular'

### ISSUE THREAD

**Issue by steven-varga** [JuliaCollections/DataStructures.jl#338]
CircularDeque behaves differently from BOOST circular buffer  as insertion doesn't shift+overwrite existing elements in container. 

BOOST:  http://www.boost.org/doc/libs/1_61_0/doc/html/circular_buffer/example.html  as
WIKPIPEDIA: https://en.wikipedia.org/wiki/Circular_buffer

SSCCE:

```
cb = CircularDeque{Float32}(3)
# push!(a, 10)     add an element to the back
for i=1:4 push!(v,i); end   #  push! results in ERROR: 'BoundsError'

unshift!(a, 20)   add an element to the front
for i=1:4 unshift!(v,i); end   # same Bounds error
```

 
```
julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge
```)

**Comment by oxinabox** [comment]
DataStructures provides two structures:
CircularDeque and CircularBuffer.
I believe CircularBuffer provides the circular buffer behavour your are expecting.

CircularDeque provides the Fixed max-size dequeue behavour.

**Comment by steven-varga** [comment]
ok.. thanks. Did you notice that the documentation states that CircularDeque is based on 'circular buffer'? AFAIK Circular/ring buffers have concrete meaning in computer science.
