### ISSUE TITLE
Redirect (or at least make as outdated) the ReadTheDocs site

### ISSUE THREAD

**Issue by oxinabox** [JuliaCollections/DataStructures.jl#355]
Now that #347 is merged and working :tada:
we should deal with the old docs site: http://datastructuresjl.readthedocs.io/en/latest/
While it doesn't kill us to have it still running, it might confuse people.
I suggest either it should redirect,
or if that is not possible, then it should display a banner on each page saying _"Current Docs have now moved to http://juliacollections.github.io/DataStructures.jl/latest/"_

I don't know how often it is linked to online.
Probably at least a few times on blog posts and stack-overflow,
but I suspect not many.

**Comment by scls19fr** [comment]
I've added http://juliacollections.github.io/DataStructures.jl/latest/ to Google https://www.google.com/webmasters/tools/submit-url

with https://www.google.fr/search?q=datastructures.jl

http://juliacollections.github.io/DataStructures.jl/latest/ is before RTD

but not with https://www.google.fr/search?q=datastructuresjl

**Comment by scls19fr** [comment]
Maybe @ericholscher or @agjohnson or @humitos could help on this to redirect RTD pages. We are leaving their service but we were quite happy with it before... we just leave it because Documenter.jl provides instruction to build doc from Travis and host on GitHub page.

**Comment by scls19fr** [comment]
see https://docs.readthedocs.io/en/latest/team.html

**Comment by scls19fr** [comment]
Given that we have no information about how to redirect from RTD to GH pages, we should simply consider removing doc from RTD or, at least, set visibilty from "Public" to "Private"

**Comment by scls19fr** [comment]
Who can remove old doc from RTD?
because old doc is worst than no redirect

**Comment by humitos** [comment]
> Who can remove old doc from RTD?

You can remove the docs by deleting the project itself.

**Comment by humitos** [comment]
> Maybe @ericholscher or @agjohnson or @humitos could help on this to redirect RTD pages

The redirection submenu under "Admin" settings is not enough to redirect the old docs to the current ones (hosted in another domain)?

**Comment by rawls238** [comment]
Sorry, did not see the tag earlier. I can remove the RTD page.

**Comment by scls19fr** [comment]
Great @rawls238

**Comment by rawls238** [comment]
RTD has been removed so closing this issue. Thanks for pointing this out.

**Comment by scls19fr** [comment]
Thanks @rawls238

**Comment by scls19fr** [comment]
I've just ask http://datastructuresjl.readthedocs.io/ to be removed from Google indexes using https://www.google.com/webmasters/tools/removals
