### ISSUE TITLE
collect interface does not work for PriorityQueue

### ISSUE THREAD

**Issue by sambitdash** [JuliaCollections/DataStructures.jl#369]
There is no way to iterate over a PriorityQueue and collect the data into an array. Theoretically, is the correct behavior but copying over to an array from a data structure through collect or any such interface is desirable as well.
```
v=[]
while(!isempty(pq))
     push!(v, pop!(pq))
end
```
will do the job but `collect` looks like a more of a convenience API.

**Comment by sambitdash** [comment]
`collect` interface works but does not produce a sorted list now. The current behavior documented below:

```
julia> pq["a"] = 10; pq["b"] = 5; pq["c"] = 15; pq
PriorityQueue{Any,Any,Base.Order.ForwardOrdering} with 3 entries:
  "c" => 15
  "b" => 5
  "a" => 10

julia> collect(pq)
3-element Array{Pair{Any,Any},1}:
 "c" => 15
 "b" => 5 
 "a" => 10
```
I guess expected would be `["b" => 5, "a" => 10, "c" => 15]`

**Comment by kmsquire** [comment]
It does look like iteration was only [implemented as unordered implementation](https://github.com/JuliaCollections/DataStructures.jl/blob/e0cc5d0507648618a0aac9ce382f05c2fc732525/src/priorityqueue.jl#L343-L352).

Care to make a PR to change it to ordered iteration?  That will also fix `collect`.

**Comment by sambitdash** [comment]
No problems. Will do. Thanks.

**Comment by sambitdash** [comment]
Closing as the PR is now merged.
