### ISSUE TITLE
delete! in sorted containers incompatible with Dict and Set

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaCollections/DataStructures.jl#387]
The statement `delete!(d,k)`, where `d` is a `Dict` or `Set` and `k` is a key,  does not throw a key error even when `k` is missing from `d`.  (In this case,  it is a no-op.)  On the other hand, SortedSet and SortedDict, throw a key error in this circumstance.  Because these packages have been around for awhile, possibly someone is counting on this incompatible behavior, so I don't know whether to modify these containers to bring them in line with Dict.  One subtlety: `Dict` and `Set` are not necessarily typed, whereas SortedDict and SortedSet are almost always typed.  So one corner case is `delete!(s,k)` where `s`  has keytype `K`, and `k` is not convertible to `K`.

**Comment by oxinabox** [comment]
From: https://github.com/JuliaCollections/DataStructures.jl/pull/571#issuecomment-594146622
> Notice that there is an inconsistency with delete! that I didn't fix because I was afraid it would be a breaking change: #387

It is the general concensus that
turning errors into non-errors is not a breaking  change.

**Comment by NHDaly** [comment]
> One subtlety: `Dict` and `Set` are not necessarily typed, whereas SortedDict and SortedSet are almost always typed. So one corner case is `delete!(s,k)` where `s` has keytype `K`, and `k` is not convertible to `K`.


I would agree that this "strongly typed" key functions is a feature of SortedDict/SortedSet, and so I think we can keep this behavior while still claiming to implement Base.AbstractDict / AbstractSet. It seems reasonable to me to allow `delete!` nonexistent keys _only when_ they're a subtype of `K`. 👍

**Comment by NHDaly** [comment]
Okay, i've opened https://github.com/JuliaCollections/DataStructures.jl/pull/607, which does exactly this.
