### ISSUE TITLE
WeakObjectIdDict & more general dicts

### ISSUE THREAD

**Issue by mauro3** [JuliaCollections/DataStructures.jl#42]
I'm looking for a weak object-id dict for JuliaLang/julia/pull/5572.  There is one implementation here: JuliaLang/julia/issues/3002.  One feature needed is that it also works with immutable keys.

A potentially general way to go about this is to add two features to HashDict:
- possibility of key transformation: For this case it would be key -> WeakRef(key).  (This is essentially what the `add_weak_key` function in Base does.)
- possibility of adapting the `hashindex` function.  For object-id it would look:
  `hashindex(key, sz) = (int(hash(object_id(key))) & (sz-1)) + 1`

I'm not sure how to go about this:  The usual way would be to use dispatch on the functions: `hashindex(::Associative, key, sz) = (int(hash(key)) & (sz-1)) + 1`.  However, because `HashDict` is wrapped this does not work (or at least I cannot see how).  Any ideas on how to go about this?

**Comment by oxinabox** [comment]
I think this is stalled and can be closed?
