### ISSUE TITLE
Latest doc is not autodeployed

### ISSUE THREAD

**Issue by scls19fr** [JuliaCollections/DataStructures.jl#430]
Hello,

I noticed that doc is not autodeployed.

Here is an example:

In the following Markdown file of doc (in master branch)
https://github.com/JuliaCollections/DataStructures.jl/blob/master/docs/src/stack_and_queue.md
we can see
```julia
s =  Stack{Int}()
```

but in the HTML generated doc

http://juliacollections.github.io/DataStructures.jl/latest/stack_and_queue.html

we can see

```julia
s = Stack(Int)
```
(which is a deprecated syntax)

This is `latest` doc which should reflect master, isn'it?

Kind regard

**Comment by mortenpi** [comment]
The repo has dropped CI on Julia 0.6. You need to update `make.jl` accordingly -- the `julia` argument in `deploydocs` is out of date:

https://github.com/JuliaCollections/DataStructures.jl/blob/bdbcd7fa8de9c7f6ae6bf45e94e099c5f00896d6/docs/make.jl#L28-L35

**Comment by scls19fr** [comment]
Thanks @mortenpi for this idea.
I have just update this parameter of `deploydocs`. Let's wait and see if it fix this issue.

**Comment by scls19fr** [comment]
Great we can see in http://juliacollections.github.io/DataStructures.jl/latest/stack_and_queue.html


    s = Stack{Int}()

instead of

    s = Stack(Int)

so we can deduct that doc is updated.

Moreover https://github.com/JuliaCollections/DataStructures.jl/tree/gh-pages latest directory was updated recently.

Thanks again @mortenpi 
Noone here noticed that!

**Comment by scls19fr** [comment]
Same as #526
