### ISSUE TITLE
Bad rendering of DefaultDict doc

### ISSUE THREAD

**Issue by scls19fr** [JuliaCollections/DataStructures.jl#436]
Hello,

I shouldn't have merge https://github.com/JuliaCollections/DataStructures.jl/pull/431 !
Sorry about that!

With lastest master version of Documenter we are still facing bad rendering

```
julia> dd = DefaultDict{AbstractString, Vector{Int}}(Vector{Int})
DefaultDict{AbstractString,Array{Int64,1},DataType} with 0 entries

┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0

julia> push!(dd["A"], 1)
1-element Array{Int64,1}:
 1

┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0
```

Pinging @fredrikekre @mortenpi from 

Kind regards

**Comment by scls19fr** [comment]
That's just warnings... we can live with that but without warnings, doc looks better

**Comment by mortenpi** [comment]
FWIW, I can't replicate this (I don't see it in the hosted docs, nor when I build locally).

**Comment by fredrikekre** [comment]
Start julia with `julia --depwarn=error` and you will get a tracktrace to the warning.

**Comment by scls19fr** [comment]
There is still warnings on my local build of doc `file:///home/scls/.julia/dev/DataStructures/docs/build/default_dict.html`
About hosted doc... problem is https://github.com/JuliaCollections/DataStructures.jl/issues/430
About using `julia --depwarn=error` we first need to tackle https://github.com/JuliaCollections/DataStructures.jl/issues/433

**Comment by scls19fr** [comment]
http://juliacollections.github.io/DataStructures.jl/latest/default_dict.html

We are still seeing

    ┌ Warning: Deprecated syntax `underscores as an rvalue`.
    └ @ none:0

https://github.com/JuliaCollections/DataStructures.jl/tree/gh-pages was updated 2 minutes ago...

So there is still an issue with that

**Comment by fredrikekre** [comment]
Seems to only happen on Travis then.

**Comment by scls19fr** [comment]
That's odd because I don't see it now on my local build. But you are right we are still seeing this on Travis!

**Comment by fredrikekre** [comment]
Can you try changing `julia = "0.7"` to `julia = "1.0"` in `docs/make.jl`?

**Comment by fredrikekre** [comment]
So just build the docs on 1.0 where deprecations are removed then :stuck_out_tongue:

**Comment by scls19fr** [comment]
That's not a big problem for now.
I will keep it like that. Could you open an issue on Documenter.jl
and ping me when you find a fix ?
So we could test that here

**Comment by mortenpi** [comment]
> maybe I should add 1.0 to .travis.yml also (nightly is not enough)

Yes. Also make sure that all your scripts support 1.0.. there is a "Pkg missing" error on the nightly. The [Travis logs](https://travis-ci.org/JuliaCollections/DataStructures.jl) generally have all the logs that help debugging such problems.

> when you find a fix ?

Not 100% this will happen. This might be a weird 0.7-only thing (e.g. some interaction with how deprecations are implemented).

**Comment by laborg** [comment]
The bug was closed on Documenter.
