### ISSUE TITLE
failure of reuqirements from NamedTuples

### ISSUE THREAD

**Issue by jingpengw** [JuliaCollections/DataStructures.jl#444]
I was trying to use DataStructures in Julia 0.7, but failed in NamedTuples.jl.
```
ERROR: Unsatisfiable requirements detected for package NamedTuples [73a701b4]:
 NamedTuples [73a701b4] log:
 ├─possible versions are: [0.0.1-0.0.3, 0.1.0, 1.0.0, 2.0.0, 2.1.0, 3.0.0-3.0.3, 4.0.0-4.0.2] or uninstalled
 ├─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with IndexedTables [6deec6e2] to versions: [2.1.0, 3.0.0-3.0.3, 4.0.0-4.0.2] — no versions left
   └─IndexedTables [6deec6e2] log:
     ├─possible versions are: [0.1.0-0.1.8, 0.2.0-0.2.1, 0.3.0, 0.3.2-0.3.4, 0.4.0-0.4.6, 0.5.0-0.5.2, 0.6.0, 0.7.0-0.7.4] or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.8, 0.2.0-0.2.1, 0.3.0, 0.3.2-0.3.4, 0.4.0-0.4.6, 0.5.0-0.5.2, 0.6.0, 0.7.0-0.7.4]
```
It seems that there is no requirement of NamedTuples, not sure where it come from. I can use other packages, such as Query.jl, which requires NamedTuples.jl

the package test is not running in travis.

https://github.com/JuliaCollections/DataStructures.jl/blob/master/.travis.yml#L15

**Comment by kmsquire** [comment]
Not sure about the NamedTuples error, but the package tests are running fine. When the line you pointed out is commented out, the default test script is run, which runs the tests.

**Comment by scls19fr** [comment]
https://travis-ci.org/JuliaCollections/DataStructures.jl/jobs/421187906#L557 confirms that tests are running in Travis

**Comment by jingpengw** [comment]
the issue comes from IndexedTables.jl, close here.
