### ISSUE TITLE
update Value at a Key of SortedDict

### ISSUE THREAD

**Issue by sonolac** [JuliaCollections/DataStructures.jl#486]
Currently, given a SortedDict, if I want to update Value at a Key, I need to delete! the Key and insert! the (Key, NewValue). Should we be able to update the Value to NewValue instead?

```
sDic = SortedDict{Int64, Float64}()
insert!(sDic, 1, 0)
insert!(sDic, 4, 26.0)
delete!(sDic, 1)
insert!(sDic, 1, 1.0)
```

I tried sDic.bt.data[4].d = 1.0, but KDRec is immutable. Can we make the 'd' field in KDRec to be mutable?

**Comment by StephenVavasis** [comment]
You can use: `sDec[1] = 1.0`.  (If you prefer function-call syntax, you can use `setindex!`).
