### ISSUE TITLE
Add documentation for FenwickTree

### ISSUE THREAD

**Issue by eulerkochy** [JuliaCollections/DataStructures.jl#491]
With #485 in the master, there is a need for documenting this DS.

**Comment by kmsquire** [comment]
Whoops... should have asked you to do that before merging.  Oh, well, if you could add some documentation, that would be great--thanks!

**Comment by eulerkochy** [comment]
Ok, cool!

**Comment by sambitdash** [comment]
I feel the data structure should be called "BinaryIndexedTree" or something similar. In general the package contains very few DS that are named after the inventor. @eulerkochy and @kmsquire, please suggest if that change is useful.

**Comment by eulerkochy** [comment]
Why not honour the inventor when there is a scope of doing so! imo, it hardly would matter if we rename it, as both terms are quite interchangebly, plus it has been mentioned in the implementation of the DS.
```julia
struct FenwickTree{T}
    bi_tree::Vector{T} #bi_tree is shorthand for Binary Indexed Tree, an alternative name for Fenwick Tree
    n::Int
end
```
