### ISSUE TITLE
Deprecate then Remove ClassifierCollections

### ISSUE THREAD

**Issue by oxinabox** [JuliaCollections/DataStructures.jl#496]
`ClassifierCollection`s is just a really weird data structure,
that I do not think is at all standard;
and I would be surprised if any julia code compatible with the current version of DataStructures was using it.

Please correct me if I am wrong.

It was added in
 https://github.com/JuliaCollections/DataStructures.jl/commit/064e5732df60d83256c1c852cf9f84dc13e5c39d
and basically had not changed since.
It has been in this package since before we had things like PRs being used by maintainers.
Wildwest days.

Somethings were added because they seemed useful for various projects and needed to go *Somewhere*.
(Similar for some of the weirder stuff in other old packages like StatsBase)
But now this is a package with over 750 dependents,
so we should try and keep to something vaguely standard.

**Comment by oxinabox** [comment]
I do not see what purpose it servers that a `DefaultDict(Vector)` couldn't.

**Comment by oxinabox** [comment]
@lindahua  thoughts?

**Comment by kmsquire** [comment]
I think you can go ahead and remove it. Dahua hasn't been active here in a long time.
