### ISSUE TITLE
Could you have a look at RedBlackTrees.jl?

### ISSUE THREAD

**Issue by pygy** [JuliaCollections/DataStructures.jl#5]
I ported [this C red black tree library](http://eternallyconfuzzled.com/libs/jsw_rbtree.zip), (see [here](http://eternallyconfuzzled.com/tuts/datastructures/jsw_tut_rbtree.aspx) for a complete description), and I'd like to know if you're interested in adding it to this package.

https://github.com/pygy/RedBlackTrees.jl

It implements `push!()`, `delete!()`, `in()`, `size()`, `length()`, `show()` and the iterator protocol.

A tree is created using `RedBlackTree(some_type)`. You can iterate backwards using `for i in RedBlackTrees.Backward(tree) ...`

`show(tree)` only displays the type and size of the tree. You can see the content of the tree using `show(tree.root)`.

On my machine, insertion beats `push!(array, item); sort!(array)` from ~3000 items on.

I'll add the possibility to pass custom `cmp()` and `copy()` functions (`copy` for node insertion). Currently, it uses `Base.cmp` and doesn't make any copy.

There are probably some more things left to tweak. For example, according to `@time` iteration allocates ~ 400 bytes per item in the tree, even though it shouldn't.

It's also the first time I use parametric types, and I may have overused parametric function definitions.

At last, I use an `alias RBLNode Union(RBNode{T}, Nothing)` as the type for nodes, with Nothing representing leafs. It may or may not help to use an abstract type and have both RBNode and Leaf depend on it, but it would require some tweaks since the nodes are parametrized, I'd have to keep a typed leaf around, or create one each time I need one, which may slow things down.

**Comment by hayd** [comment]
Did this work ever get pushed anywhere?

**Comment by StephenVavasis** [comment]
The sorted containers are based on 2-3 trees, which are mostly functionally equivalent to red-black trees (although the latter may have a performance edge).  If someone wants to implement the sorted containers using red-black trees as the substrate, there may be a performance boost.  However, my own timing tests seem to indicate that the main performance drag on the currently implemented 2-3 trees is main-memory fetching (i.e., cache misses).  Therefore, it may be more profitable to implement something like Bender et al.'s cache-oblivious B-trees, SIAM J. Comput., 2005.

**Comment by oxinabox** [comment]
Since this hasn't been touched since 2014, shall it just be closed?
A new PR could be opened later.
