### ISSUE TITLE
`sizehint!` is not implemented for heaps

### ISSUE THREAD

**Issue by harryscholes** [JuliaCollections/DataStructures.jl#518]
The heap interface specification says that `sizehint!` methods should be implemented for heaps but they aren't. I can add these at the hackathon tomorrow

https://github.com/JuliaCollections/DataStructures.jl/blob/8ec394cba8561a42e1241dfde99f77ee4b7159af/src/heaps.jl#L25

**Comment by oxinabox** [comment]
Good catch,
Should be an easy PR if you are interest.
