### ISSUE TITLE
Documentation on github.io not picking-up changes

### ISSUE THREAD

**Issue by milesfrain** [JuliaCollections/DataStructures.jl#526]
Looks like [this change](https://github.com/JuliaCollections/DataStructures.jl/commit/f314a5e6dcb52aa89ab6ee19bc335f4a9b2d0cec#diff-5d4f35ce5e5ce0a4b97132547250b050) is still not reflected in the [github.io docs](https://juliacollections.github.io/DataStructures.jl/latest/heaps.html).
The constructor sections still appears as:
```
h = binary_minheap(Int)
h = binary_maxheap(Int)            # create an empty min/max binary heap of integers

h = binary_minheap([1,4,3,2])
h = binary_maxheap([1,4,3,2])      # create a min/max heap from a vector

h = mutable_binary_minheap(Int)
h = mutable_binary_maxheap(Int)    # create an empty mutable min/max heap

h = mutable_binary_minheap([1,4,3,2])
h = mutable_binary_maxheap([1,4,3,2])    # create a mutable min/max heap from a vector
```
Does something need to be fixed in the [travis config](https://github.com/JuliaCollections/DataStructures.jl/blob/b6599bc41c34c7f1dbc095c20ccb6f163bff4c97/.travis.yml#L21)?

**Comment by kmsquire** [comment]
Thanks for pointing this out.  It looks like we haven't built documentation since v0.14 (and we're on v0.17).

I updated the documentation setup and build keys in github and travis-ci, and made some minor updates in #527--hopefully this will fix things.
