### ISSUE TITLE
Packed(Sparse?)IntSet Implementation

### ISSUE THREAD

**Issue by louisponet** [JuliaCollections/DataStructures.jl#532]
I've recently played around with implementing something like:
[Sparse Set (geeksforgeeks)](https://www.geeksforgeeks.org/sparse-set/),
but without the maximum value limitation and with a paging mechanism to make the reverse actually sparse.The idea is to have fast insertion, `in` operations but also very fast iteration over which indices are actually occupied.

I was wondering if this could find a place here, I can clean up the code and make decent tests for it. There are also the mathematical set functions that I didn't really need and thus didn't implement yet, but I wouldn't mind doing so if there's interest.

I'm using this to handle the indexing for an entity component system, and it seems to be pretty fast and reliable. There is also a fast zip-like iterator that returns the positions in the packed array that correspond to the same index, this can be then used with different component vectors for example. The current implementation is here:
[PackedIntSet](https://github.com/louisponet/PStdLib.jl/blob/master/src/datastructures/PackedIntSet.jl)

**Comment by oxinabox** [comment]
Yes, PR would be welcomed
