### ISSUE TITLE
Document why DefaultDict with Float64[] default has default change after push! to values

### ISSUE THREAD

**Issue by ianfiske** [JuliaCollections/DataStructures.jl#542]
Create a `DefaultDict` with Vector{Float64} values and an empty array as default.  Then push a number onto the key "a".
```
d = DefaultDict{String, Vector{Float64}}(Float64[])
push!(d["a"], 1)
```
But now, the key "b" defaults to the value of the key "a":
```
julia> d["b"]
1-element Array{Float64,1}:
 1.0
```
It seems like the default value changed to the last value-array that was modified.  Incidentally, this does _not_ happen if the default value is `[]` instead of `Float64[]`.

**Comment by oxinabox** [comment]
Youi wanted: 
```
d = DefaultDict{String, Vector{Float64}}(()->Float64[])
```
or equivelently
```
d = DefaultDict{String, Vector{Float64}}(Vector{Float64})
```

See also:
https://discourse.julialang.org/t/unexpected-behaviour-in-nested-defaultdicts/29440/2

**Comment by ianfiske** [comment]
Interesting.  Thanks for the reply and pointer towards an explanation.

**Comment by oxinabox** [comment]
related #541

**Comment by laborg** [comment]
Was documented in https://github.com/JuliaCollections/DataStructures.jl/pull/730 and will very likely not be backported to 0.18
