### ISSUE TITLE
CircularDeque: shouldn't `front` and `back` be `first` and `last`?

### ISSUE THREAD

**Issue by sairus7** [JuliaCollections/DataStructures.jl#544]
`front(a)            # get the element at the front`
`back(a)             # get the element at the back`

But for other arrays there are different notations - `first` and `last`

**Comment by oxinabox** [comment]
Yes, let's change that.
Make a PR deprecating them, and a minor release.

And sometime later I will do a depreciation round and remove them

**Comment by sairus7** [comment]
By the way, what's difference between CircularDeque and CorcularBuffer? Looks like the latter covers all functionality of the former?

**Comment by oxinabox** [comment]
If you overfill a `CircularDeque` you get a am error.
If you overfill a `CircularBuffer` it overwrites the older data.

Buffers have uses in a few places where losing old data doesn't matter.
Like audio processing.
If you fallbehind it is better to just give up on the oldest ones.

**Comment by clement-f** [comment]
This issue has been solved by #565. It can be closed.
