### ISSUE TITLE
Duplicate comments on pop! in documentation

### ISSUE THREAD

**Issue by metab0t** [JuliaCollections/DataStructures.jl#559]
https://github.com/JuliaCollections/DataStructures.jl/blob/7ad2cf690ca3bc09c55162c7bbe3e99b477ba1b4/src/sorted_dict.jl#L464-L471
https://github.com/JuliaCollections/DataStructures.jl/blob/7ad2cf690ca3bc09c55162c7bbe3e99b477ba1b4/src/sorted_set.jl#L238-L245

Two comments are the same and cause some confusion in documentation. Is it intended?

**Comment by laborg** [comment]
Has been fixed. See https://github.com/JuliaCollections/DataStructures.jl/issues/647
