### ISSUE TITLE
Accumulator has non-parseable `repr`

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaCollections/DataStructures.jl#573]
```julia
julia> using DataStructures

julia> x = [1, 1, 2, 2, 3];

julia> counter(x)
Accumulator{Int64,Int64} with 3 entries:
  2 => 2
  3 => 1
  1 => 2

julia> repr(counter(x))
"Accumulator(2 => 2,3 => 1,1 => 2)"

julia> Accumulator(2 => 2,3 => 1,1 => 2)
ERROR: MethodError: no method matching Accumulator(::Pair{Int64,Int64}, ::Pair{Int64,Int64}, ::Pair{Int64,Int64})
```
the valid constructor using `Pair`s is 
```julia
julia> Accumulator(Dict(2 => 2,3 => 1,1 => 2))
Accumulator{Int64,Int64} with 3 entries:
  2 => 2
  3 => 1
  1 => 2
```

Also the printing is missing a space after `,`:
```julia
(2 => 1,1 => 1)
```
should be
```julia
(2 => 1, 1 => 1)

**Comment by nickrobinson251** [comment]
is this better fixed by changing the printing or by making `Accumulator(2 => 2, 3 => 1 ,1 => 2)` a valid constructor?

**Comment by kmsquire** [comment]
Making `Accumulator(2 => 2, 3 => 1 ,1 => 2)` a valid constructor seems reasonable.  I believe the printing is falling back on the default for `AbstractDict`.

**Comment by karan0299** [comment]
May I take up this issue?
Thanks!

**Comment by oxinabox** [comment]
Go ahead, do read the docs on how to overload `show` carefully

**Comment by nickrobinson251** [comment]
Making `Accumulator(2 => 2, 3 => 1 ,1 => 2)` a valid constructor seems a better approach than changing `show`, no?

**Comment by oxinabox** [comment]
Oh, yes, that does seem better
