### ISSUE TITLE
Prepare for release 0.18

### ISSUE THREAD

**Issue by oxinabox** [JuliaCollections/DataStructures.jl#577]
#578 requires release of a breaking version.

List of other things we want to do before releasing 0.18:
 - [x] Delete deprecated `ClassifierCollection` 
 - [x] Delete all things in `deprecations`
 - [ ] deprecate `find_root` (see #603 )

**Comment by oxinabox** [comment]
#547  also requires a breaking release.

**Comment by davidanthoff** [comment]
Is there some way for me to relatively figure out what was breaking in 0.18?

I got a bunch of CompatHelper notifications in my packages asking whether I want to add 0.18 to the list of compatible packages. So now I go to this repo here, and see a CHANGELOG, hurray, that should help me make that decision. Ok, the CHANELOG directs me to the releases. I look there, and I see a bunch of releases and PRs merged etc., but it is really not clear from that why this was a breaking release, what I need to be aware of in making the update decision.

I could see two good general solutions for this: a) either add `[BREAKING]` to those PRs and issues that are breaking, that would make it relatively easy to look at the auto-generated release notes for releases and figure out what I need to look at, or b) just write a very short release not for breaking releases that tell people that get the CompatHelper notification what actually broke.

**Comment by oxinabox** [comment]
Yeah,we could do that better.

The breaking changes are:
 - removal of things that were deprecated like `top`
 - Heap type parameters and constructors.

**Comment by davidanthoff** [comment]
Thanks!

I think this is actually a general problem across the ecosystem, but I don't really have a very good idea how to solve it... Maybe TagBot could open an issue whenever a breaking release is tagged that is called "Update release notes with information what was breaking" or something like that...

**Comment by oxinabox** [comment]
I think moving forward I will at least attach a breaking label to each PR.
and maybe rename them
