### ISSUE TITLE
Rename DisjointSets to DisjointSet ? 

### ISSUE THREAD

**Issue by oxinabox** [JuliaCollections/DataStructures.jl#579]
The fact that DisjointSets is a collection of sets under the hood is not relevent to the user.
The API is that of a `AbstractSet`.
The implementation is a implementation detail that is actually completely invisible to the user AFAICT

**Comment by oxinabox** [comment]
@c-p-murphy did you ever make a PR to do this?
I can't find it

**Comment by c-p-murphy** [comment]
Hey @oxinabox—no, sorry, things got hectic this past semester with everything going on in the world and I lost track of it. I'll try to finish putting something together over the next week or so and then submit a PR. Thanks for the reminder.

**Comment by oxinabox** [comment]
Cool I might hold off releasing 0.18 for this so can get the deprecations in.
cf #577

**Comment by oxinabox** [comment]
@c-p-murphy any update? I wouls still like to get this in before tagging 0.18

**Comment by laborg** [comment]
Already fixed by https://github.com/JuliaCollections/DataStructures.jl/pull/700
