### ISSUE TITLE
BoundsError in MutableBinaryHeap delete!

### ISSUE THREAD

**Issue by ancapdev** [JuliaCollections/DataStructures.jl#611]
If run with ```--check-bounds=yes```, the following throws ```BoundsError```:
```Julia
x = MutableBinaryMinHeap{Int}()
h1 = push!(x, 1)
h2 = push!(x, 2)
delete!(x, h2)
```
[Offending line](https://github.com/JuliaCollections/DataStructures.jl/blob/v0.17.13/src/heaps/mutable_binary_heap.jl#L116)
```Julia
        @inbounds nodes[nd_id] = new_rt = pop!(nodes)
```

Looks to happen when deleting from the end of the heap. The code is safe under the assumption that ```pop!(::Vector)``` doesn't resize underlying storage, but not ideal to have this throw when bounds checks are forced.

**Comment by oxinabox** [comment]
Yes, the this is definately a bug.
Do you want to make a small PR to fix it, since you have found it now?
