### ISSUE TITLE
deque method definition overwritten

### ISSUE THREAD

**Issue by harryscholes** [JuliaCollections/DataStructures.jl#614]
In v0.17.14 I'm seeing this warning
```
WARNING: Method definition deque(Type{T}) where {T} in module DataStructures at /home/runner/.julia/packages/DataStructures/w35Mo/src/deque.jl:89 overwritten at deprecated.jl:65.
  ** incremental compilation may be fatally broken for this module **
```

_Originally posted by @giordano in https://github.com/JuliaCollections/DataStructures.jl/pull/609#issuecomment-621216809_

I think this is happening because @deprecate exports the deprecated function, but deque is still exported in DataStructures.jl.

**Comment by giordano** [comment]
>  but deque is still exported in DataStructures.jl.

Does this method have the same signature as the deprecated one?

**Comment by harryscholes** [comment]
Yes, it's `deque(::Type{T}) where T`

**Comment by giordano** [comment]
Then removing the export doesn't help.  The deprecated method is overriding that one

**Comment by harryscholes** [comment]
Oh of course. Do I need to remove the method definition for `deque` in `src/deque.jl`?

**Comment by giordano** [comment]
Is this one https://github.com/JuliaCollections/DataStructures.jl/blob/48ba4d056248399f4ad0b8f321bd7f441e4fe60b/src/deque.jl#L84-L89?  I gues so

**Comment by harryscholes** [comment]
Yep, that's the method definition
