### ISSUE TITLE
use and export of path

### ISSUE THREAD

**Issue by yakir12** [JuliaCollections/DataStructures.jl#633]
in 
https://github.com/JuliaCollections/DataStructures.jl/blob/0d9cb40acc0e2898fb57022c54bf4432f495ce96/src/DataStructures.jl#L44
you export the function `path`. As `DataStructures` is a widely used package (by other packages) and `path` being a pretty basic widely used variable/function name, would you consider unexporting the function or replacing its name?
Super easy fix on my end of things, but I can imagine this will trip others as well.

**Comment by kmsquire** [comment]
That seems reasonable to me. Since I think this has been there for a while, I’m wondering if there is a better name this could be deprecated to for a release cycle.

**Comment by oxinabox** [comment]
What's a good name for it?
`trie_path` seems like a good default to fall back to.
But I wonder if there is another option.

**Comment by oxinabox** [comment]
Looking at the code it is unclear to me as to if it is even a useful operation.
It gives back all of the tries in the path for the string, until it can't find one?

If so `partial_path` would be better.
But still not sure it should be user-facing, (and we don't use it internally either).

User facing would be something like `longest_prefix` which would do the same but return a string?

**Comment by oxinabox** [comment]
Proposal: we deprecate it to a no exported `DataStructure.partial_path` and put the depreciation warning message that we are considering removing it from the package, and link to an issue where people can object, and if no one does we remove it in 0.19

**Comment by oxinabox** [comment]
@yakir12  what do you think of my proposal above?
Would you be interested in making a PR to make that so?

**Comment by yakir12** [comment]
Sounds great. I'll be glad to. Can't before next week though.

**Comment by oxinabox** [comment]
I will wait for this to do #577
