### ISSUE TITLE
Triplicates of function description in documentation

### ISSUE THREAD

**Issue by pauljurczak** [JuliaCollections/DataStructures.jl#647]
Documentation page https://juliacollections.github.io/DataStructures.jl/latest/sorted_containers/#Base.first-Tuple{SortedDict} contains triplicates of Base.first and Base.last:

![Screenshot from 2020-08-06 18-08-25](https://user-images.githubusercontent.com/4933032/89594726-e0738e80-d80f-11ea-9224-c4c9dd63e7a4.png)

**Comment by laborg** [comment]
This is fixed on master and its unlikely that this will be backported to 0.18.
