### ISSUE TITLE
Revising sorted collections documentation

### ISSUE THREAD

**Issue by oxinabox** [JuliaCollections/DataStructures.jl#667]
_Originally posted by @StephenVavasis in https://github.com/JuliaCollections/DataStructures.jl/issues/479_  (moved here since not directly related to the high level roadmap to 1.0)

I would like to make some small revisions to the documentation for sorted containers (see e.g. https://github.com/JuliaCollections/DataStructures.jl/issues/528).  I don't know how to do this, i.e., I don't know which file I should edit because I don't understand how the docs are organized and populated.  Any pointers would be appreciated.

**Comment by oxinabox** [comment]
@StephenVavasis  Sorted container docs are in https://github.com/JuliaCollections/DataStructures.jl/blob/master/docs/src/sorted_containers.md

The docs are built locally via:

1. Navigate to the `docs` directory .`cd docs`
2. Start julia with the docs directory set as the active project. `julia --project=.`
3. Run `] up` (can skip this if already done recently)
4. Run: `include("make.jl")`
5. Files will appear in `docs/build/index.html`

CI runs something similar, but also deploys them

**Comment by StephenVavasis** [comment]
Closed via #787
