### ISSUE TITLE
BinaryMaxHeap{Int64}() isa BinaryMaxHeap{Int64} == false

### ISSUE THREAD

**Issue by dillondaudert** [JuliaCollections/DataStructures.jl#686]
In PR #673, the constructors of `BinaryHeap` were changed to instantiate `Base.Ordering` singleton types and then use those as parameters. This broke the following pattern:

```julia
# on 0.18.4
julia> foo(::BinaryMaxHeap) = "foo"
julia> foo(BinaryMaxHeap{Int}())
"foo"
```

```julia
# on 0.18.5
julia> foo(::BinaryMaxHeap) = "foo"
julia> foo(BinaryMaxHeap{Int}())
ERROR: MethodError: no method matching foo(::BinaryHeap{Int64,Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}})
Closest candidates are:
  foo(::T) where T<:(BinaryHeap{T,Base.Order.ReverseOrdering} where T) at REPL[16]:1
Stacktrace:
 [1] top-level scope at REPL[17]:1
```

I noticed this when my tests started failing in NearestNeighborDescent.jl unexpectedly, since the compat is set to "0.18". Let me know if this was intentional / breaking.

**Comment by oxinabox** [comment]
Isolated what is going on:
`BinaryMaxHeap{Int64}()` does not actually return a `BinaryMaxHeap{Int64}`
It returns something very close

```julia
julia> typeof(BinaryMaxHeap{Int64}())
BinaryHeap{Int64, Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}

julia> BinaryMaxHeap{Int64}
BinaryMaxHeap{Int64} (alias for BinaryHeap{Int64, Base.Order.ReverseOrdering})

julia> BinaryMaxHeap{Int64}() isa BinaryMaxHeap{Int64}
false
```

**Comment by dillondaudert** [comment]
Thanks for the quick fix!

Sorry about the vagueness of the initial title, btw - I'll try to be more clear in the future.

**Comment by oxinabox** [comment]
No problem, that was a weird one
