### ISSUE TITLE
recursively sort dicts

### ISSUE THREAD

**Issue by bjarthur** [JuliaCollections/DataStructures.jl#697]
if a value in a dict happens to also be a dict, it would be nice to have the option when converting it to a SortedDict that both dicts get sorted.  i could see a `recursive=False` flag added to `SortedDict(d, ...)`.  would anyone else find this useful?

**Comment by bjarthur** [comment]
or maybe sth like this:

```julia
RecursivelySortedDict(d) = SortedDict(k=>typeof(v)<:Dict ? RecursivelySortedDict(v) : v for (k,v) in d)
```

**Comment by oxinabox** [comment]
This can be accomplished via specifying the valye type to be `SortedDict`.
Which seems more ideomatic.

```julia
julia> using DataStructures

julia> x = Dict(1=>10, 2=>20);

julia> y = Dict(1=>100, 2=>200);

julia> SortedDict{Int, SortedDict}(1=>x, 2=>y)
SortedDict{Int64, SortedDict, Base.Order.ForwardOrdering} with 2 entries:
  1 => SortedDict(1=>10, 2=>20)
  2 => SortedDict(1=>100, 2=>200)

julia> SortedDict{Int, SortedDict{Int, Int}}(1=>x, 2=>y)
SortedDict{Int64, SortedDict{Int64, Int64, Ord} where Ord<:Base.Order.Ordering, Base.Order.ForwardOrdering} with 2 entries:
  1 => SortedDict(1=>10, 2=>20)
  2 => SortedDict(1=>100, 2=>200)
```

Note these are subtly different, but both are sorted

**Comment by bjarthur** [comment]
that solution only works one level deep:

```julia
julia> z = Dict(1=>1000, 2=>2000)
Dict{Int64,Int64} with 2 entries:
  2 => 2000
  1 => 1000

julia> d = Dict(1=>x, 2=>Dict(1=>y, 2=>z))
Dict{Int64,Dict{Int64,V} where V} with 2 entries:
  2 => Dict(2=>Dict(2=>2000,1=>1000),1=>Dict(2=>200,1=>100))
  1 => Dict(2=>20,1=>10)

julia> SortedDict{Int, SortedDict}(d)
SortedDict{Int64,SortedDict,Base.Order.ForwardOrdering} with 2 entries:
  1 => SortedDict(1=>10,2=>20)
  2 => SortedDict(1=>Dict(2=>200,1=>100),2=>Dict(2=>2000,1=>1000))

julia> RecursivelySortedDict(d)
SortedDict{Any,Any,Base.Order.ForwardOrdering} with 2 entries:
  1 => SortedDict{Any,Any,Base.Order.ForwardOrdering}(1=>10,2=>20)
  2 => SortedDict{Any,Any,Base.Order.ForwardOrdering}(1=>SortedDict{Any,Any,Base.Order.ForwardO…

julia> ans[2]
SortedDict{Any,Any,Base.Order.ForwardOrdering} with 2 entries:
  1 => SortedDict{Any,Any,Base.Order.ForwardOrdering}(1=>100,2=>200)
  2 => SortedDict{Any,Any,Base.Order.ForwardOrdering}(1=>1000,2=>2000)
```

can you please re-open the issue.  happy to submit a PR with my solution unless there's a better way.

**Comment by oxinabox** [comment]
It works as many levels as you declare it for.
Though you can't do that if your dict is heterogeneous.

> happy to submit a PR with my solution

While we always appreciate contributions, such a PR will not be merged.
DataStructures.jl is effectively feature frozen until it hits 1.0, at least as far as features that increase our API surface are concerned.
We have enough work right now getting the API into shape for 1.0 without expanding it.
Further, this need to be able to recursively sort nested  heterogeneous dicts after they are created seems surficently niche that the helper function you present can be put in the package where it is needed.
I can see it is definitely useful for some things, e.g. dealing with Dicts that came out of JSON or a FFI call or some such.
But not every useful thing needs to be in this package.
🙂

**Comment by StephenVavasis** [comment]
I would like to add the following point.   Each recursive level would need to define its own comparison operation.  Furthermore, child A and child B of the top level would not necessarily take the same comparison operation.   How would you specify in a single constructor call which comparisons to use at the subsequent levels?   Even if we could think of a clean way to specify this, it would be difficult to write documentation and a suitable test set.
