### ISSUE TITLE
Request for joining the organisation

### ISSUE THREAD

**Issue by akshitagupta15june** [JuliaCollections/DataStructures.jl#702]

**Comment by oxinabox** [comment]
Hi,
Joining the organisation grants merge rights.
We follow [ColPrac](https://github.com/SciML/ColPrac#becoming-a-collaborator-gaining-merge-rights)

> 
> #### Becoming a Collaborator (gaining merge rights)
> 
> *   Collaborator merge rights are typically assigned at an Organisational level for all repositories in a GitHub organisation, or at a Team level for a subset of repositories.
> *   Before becoming a collaborator it is usual to:
>     *   contribute several PRs,
>     *   review constructively and kindly several PRs,
>     *   contribute meaningfully to several discussions on issues.
> *   You may ask to be added as a collaborator.
> It is not rude to ask.
> 

I am going to be declining this request for now.


if you wish to make PRs, you don't need to join the organisation, just fork the repo and make a PR.
https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo

**Comment by timholy** [comment]
Is it possible to join with read-only rights? Not that I am aware of any advantage in doing so.

**Comment by oxinabox** [comment]
> Is it possible to join with read-only rights? Not that I am aware of any advantage in doing so.

I think it might be, but its probably a bad idea.
Its good to have the consistency that everyone who is part of the org has merge rights.
Being part of the org but not having merge rights seems like it could be used for evil, as part e.g. of a social engineering attack.
E.g. convincing people you are a co-contributor when you are not, or possibly tricking Registrator (which i think only checks if part of org)
