### ISSUE TITLE
Misleading doc for `insert!(sc, k)`

### ISSUE THREAD

**Issue by SimonCoste** [JuliaCollections/DataStructures.jl#726]
The following method call should be `insert!(sc, k, v)` and not `insert!(sc, k)`. 

https://github.com/JuliaCollections/DataStructures.jl/blob/4cc80fbce85336291900f01b985806e3821abcc6/src/sorted_multi_dict.jl#L152-L166

Also, this doc entry should be merged with this duplicate:

https://github.com/JuliaCollections/DataStructures.jl/blob/4cc80fbce85336291900f01b985806e3821abcc6/src/sorted_dict.jl#L256-L270

Another duplicate was pointed in https://github.com/JuliaCollections/DataStructures.jl/issues/559 for `pop!(sc, k)`.

**Comment by StephenVavasis** [comment]
Closed via #787
