### ISSUE TITLE
Should Compat.jl exist in Project.toml?

### ISSUE THREAD

**Issue by Datseris** [JuliaCollections/DataStructures.jl#732]
Hi, I'm wondering whether Compat.jl is used and/or necessary at the moment or it can be removed, given that we have Julia 1.0?

(it has a habit of creating some conflicts with other "old" pre-1.0 packages we are trying to update to Julia 1)

**Comment by oxinabox** [comment]
I am pretty sure we use it.
Because we have it set to the version that is for 1.x features able to be used from 1.0

You can try removing it and seeing what breaks by running the tests.
If it isn't too much we might be able to work around it.
But modifying the other packages might be a better thing

**Comment by Datseris** [comment]
Oh, sorry, my mistake, didn't know that Compat also helps for 1.x features in 1.0. Then yes, obviously other packages need to be updated.

**Comment by oxinabox** [comment]
Yeah new version of Compat only does that. Which is why it was a breaking change
