### ISSUE TITLE
Iterator for AVLTree

### ISSUE THREAD

**Issue by sirno** [JuliaCollections/DataStructures.jl#738]
I came across a weird problem, where I incrementally need to store information that is best held by an AVLTree, but once done, need to retrieve the data in order, thus I wrote a non-recursive iterator that uses a stack to track parent elements. 

If this was of general interest I can create a pr for this.

**Comment by StephenVavasis** [comment]
Note that SortedSet, SortedDict, and SortedMultiDict already have an iteration capability and are able to carry out a sequence of random insertions followed by ordered retrieval.

**Comment by sirno** [comment]
Oh that is good to know. The OrderedSet implementation does exactly what I needed. 

It seems a little odd to me, that you maintain the underlying data representations (trees, linked lists) in the same repository as collections such as ordered sets (I know what an AVLTree does for me, but the specific properties of an OrderedSet in a library that i havent used before is ambiguous). It would be very nice if the documentation contained an overview of the data structures and their respective capabilities.

I close this, because there is no need.
