### ISSUE TITLE
Bug when using Base.By(last) in a BinaryHeap

### ISSUE THREAD

**Issue by quiaro21** [JuliaCollections/DataStructures.jl#828]
I am trying to use the example in the DataStructures documentation. The code is the following:
`using DataStructures
data = collect(enumerate(["foo", "bar", "baz"]))
h2 = BinaryHeap(Base.By(last), data) # Order by 2nd element only
first(h2)                            # => (2, "bar")`

I am getting the following error:

`ERROR: MethodError: no method matching BinaryHeap(::Base.Order.By{typeof(last), Base.Order.ForwardOrdering}, ::Vector{Tuple{Int64, String}})
Stacktrace:
 [1] top-level scope
   @ ~/Desktop/ShortestPath/heaptest.jl:3`

Which is weird because I have been using Mutable Binary Heaps for a long time (using also the ordering) and I never had any problem. I have not updated Julia, and I have the latest version of Data Structures. Any ideas?

**Comment by laborg** [comment]
Can't replicate with DataStructures 0.18.15 or master on Julia 1.9.3.
Please open a new issue if this is still a problem for you (including the output of `versioninfo()`)
```
Status `~/.julia/environments/temp/Project.toml`
  [864edb3b] DataStructures v0.18.15

julia> data = collect(enumerate(["foo", "bar", "baz"]))
3-element Vector{Tuple{Int64, String}}:
 (1, "foo")
 (2, "bar")
 (3, "baz")

julia> h2 = BinaryHeap(Base.By(last), data)
BinaryHeap{Tuple{Int64, String}, Base.Order.By{typeof(last), Base.Order.ForwardOrdering}}(Base.Order.By{typeof(last), Base.Order.ForwardOrdering}(last, Base.Order.ForwardOrdering()), [(2, "bar"), (1, "foo"), (3, "baz")])

julia> first(h2)    
(2, "bar")
```
