### ISSUE TITLE
dequeue for PriorityQueue should return Key-Value Pair not just Key

### ISSUE THREAD

**Issue by micampbell** [JuliaCollections/DataStructures.jl#845]
Generally, the dequeue operation is to retrieve the value in a path-planning tree search. As currently implemented, one needs to call peek() to get to the "best" value (best is lowest or highest depending on direction), followed by dequeue!() to remove it. This is cumbersome and inefficient (two calls to get "best").
make dequeue! return the same as peek

**Comment by hdavid16** [comment]
There is `dequeue_pair!` to do this. However, I do agree that it makes sense to just have `dequeue!` do this.

**Comment by hdavid16** [comment]
I totally agree with you!

**Comment by micampbell** [comment]
well, if you think it isn't too late to change....re-opened

**Comment by hdavid16** [comment]
It looks like #479 removes these and replaces them with `popfirst!`, which behaves as `dequeue_pair!`. This is to conform with Julia base.

**Comment by aoanla** [comment]
Eh, I'm finding it very hard to work out what methods are implemented for what in what release thanks to all this churn. 

Pkg finds the current release at 0.18.15  for me, which uses `dequeue!` for PriorityQueue and does not implement `popfirst!` - at least, I am shouted at for trying to use it.

The documentation, however, merrily tells me that I should *definitely* use `popfirst!` , despite (again), this not being implemented in the release that Pkg thinks is most recent.

If this *isn't* implemented in an actually released version, can the documentation at least not *claim* this works when it doesn't yet?
