### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by hdavid16** [JuliaCollections/DataStructures.jl#855]
Hi, I noticed that the last version was tagged a year ago. I see there have been new methods added for `PriorityQueue`s (e.g. `popat!`, `popfirst!`). Probably should tag a new release to include these new features...

**Comment by oxinabox** [comment]
Those methods are being added as part of https://github.com/JuliaCollections/DataStructures.jl/issues/479 I believe.
Bug fixes are being backported to prior released versions.
