### ISSUE TITLE
IntSet tests in release-0.18 branch are broken on julia 1.9+

### ISSUE THREAD

**Issue by oxinabox** [JuliaCollections/DataStructures.jl#864]
Works fine in 1.8 but but after 1.9 it fails.
Master branch has it working fine.
I haven't looked into why

**Comment by StephenVavasis** [comment]
I have traced the problem to a bug in Base.map!.  I have opened an issue:
https://github.com/JuliaLang/julia/issues/50780

**Comment by StephenVavasis** [comment]
Sorry, I got this wrong: `map!(|,a,b)` does not replace `a` with the bitwise OR of `a` and `b` as I had assumed, as explained by the respondent to my issue https://github.com/JuliaLang/julia/issues/50780 . However, I now don't understand how `union` of IntSets ever worked.  Line 94 of int_set.jl seems to rely on the fact that `map!(|,a,b)`  replaces `a` with a bitwise OR.  I will try to return to this later.

**Comment by laborg** [comment]
The underlying issue has been fixed. This issue can be closed.
