### ISSUE TITLE
Release notes are wrong for backported `0.18` releases

### ISSUE THREAD

**Issue by Krastanov** [JuliaCollections/DataStructures.jl#865]
The `0.18` releases do not come from master anymore, rather they are being done selectively with backports to separate branches, because the master branch is dedicated to the 0.19 efforts. However, the automated release notes on the github release page lists all merges since previous release, not only the backports. E.g. 0.18.15 lists #861 as part of the release, while #861 was never backported.

This issue is to report incorrect release notes, not to complain about backporting which does take plenty of volunteer effort and is expected to be minimal.

**Comment by oxinabox** [comment]
I assume this is a bug in TagBot

**Comment by Krastanov** [comment]
reported there; closing here
