### ISSUE TITLE
Error on push! for Queue

### ISSUE THREAD

**Issue by nguiard** [JuliaCollections/DataStructures.jl#902]
Hi, I'm getting:

```
julia> using DataStructures

julia> q = Queue{Int64}()
Queue{Int64}(Deque [Int64[]])

julia> push!(q, 1)
ERROR: MethodError: no method matching push!(::Queue{Int64}, ::Int64)

...
```

Julia 10.2, DataStructures 0.18.18. `push!` on `Deque` works, but fails on `Queue`. `isempty` works... Am I missing something?

**Comment by nguiard** [comment]
If I manually copy the function definition from `queue.jl` in the repl
```julia
function Base.push!(q::Queue, x)
    push!(q.store, x)
    return q
end
```
then try again, `push!` now works... Any idea? I'm quite confused

**Comment by StephenVavasis** [comment]
For DataStructures version 0.18 (stable current release), the function to add an item to a Queue is `enqueue!`.  This is has been changed to `push!` in the DEV version of the package, which will become the stable version down the road.  If you prefer to use `push!`, then upgrade to the DEV version via: `]` at the REPL to enter Package mode, then `add DataStructures#master`.

**Comment by nguiard** [comment]
Oh! My bad, I was looking at the dev docs, effectively. Thanks and sorry for the inconvenience
